site_name: Codecheck Documentation
theme: readthedocs
use_directory_urls: true
google_analytics: ['UA-73275567-3', 'auto']

# Choices remaining: readthedocs, yeti, journal
# readable, cosmo, flatly, spacelab, cerulean, slate, mkdocs, journal = not elegantly responsive
# cyborg, united, amelia, mkdocs =  does not match codecheck color scheme
# simplex = does not match codecheck font
# bootstrap = oh my god this bootstrap implementation is blegghghghghh

pages:
- "": index.md
- Welcome: en/index.md
- Using Github: en/guide_github.md
- Using The Web Editor: en/guide_web_editor.md
# - Organizing Challenges: en/guide_organizing_challenges.md
- Reference: en/reference_users.md
# - Organizer Reference: en/reference_organizers.md
- はじめに: ja/index.md
- Webエディタの使用方法: ja/guide_web_editor.md
- Githubの使用方法: ja/guide_github.md
- チャレンジの運営: ja/guide_organizing_challenges.md
- リファレンス: ja/reference_users.md
# - 運営者リファレンス: ja/reference_organizers.md
