site_name: Codecheck Documentation

# Good themes: readthedocs, yeti, journal
# Not elegantly responsive: readable, cosmo, flatly, spacelab, cerulean, slate, mkdocs, journal
# Color does not match codecheck: cyborg, united, amelia, mkdocs
# Font does not match codecheck: simplex
# Bleh in general: bootstrap
theme: readthedocs

use_directory_urls: true

pages:
## English pages:
- "": index.md
- Welcome:                en/index.md
- Using Github:           en/guide_github.md
- Using The Web Editor:   en/guide_web_editor.md
#- Organizing Challenges: en/guide_organizing_challenges.md
- Reference:              en/reference_users.md
#- Organizer Reference:   en/reference_organizers.md
##
## Japanese Pages:
- はじめに:               ja/index.md
- Webエディタの使用方法:  ja/guide_web_editor.md
- Githubの使用方法:       ja/guide_github.md
- チャレンジの運営:       ja/guide_organizing_challenges.md
- リファレンス:           ja/reference_users.md
- リリースノート:         ja/release_notes.md
#- 運営者リファレンス:    ja/reference_organizers.md
