site_name: Codecheck Documentation
theme: readthedocs

# Choices remaining: readthedocs, yeti, journal
# readable, cosmo, flatly, spacelab, cerulean, slate, mkdocs, journal = not elegantly responsive
# cyborg, united, amelia, mkdocs =  does not match codecheck color scheme
# simplex = does not match codecheck font
# bootstrap = oh my god this bootstrap implementation is blegghghghghh

pages:
- "": index.md
- Welcome: en/index.md
- Using Github: en/guide_github.md
- Using The Web Editor: en/guide_web_editor.md
- Organizing Challenges: en/guide_organizing_challenges.md
- Reference: en/reference.md
- はじめに: ja/index.md
- Webエディタの使用方法: ja/guide_web_editor.md
- Githubの使用方法: ja/guide_github.md
- チャレンジの運営: ja/guide_organizing_challenges.md
- リファレンス: ja/reference.md
